name: Build

on: pull_request

jobs:
  build:
    runs-on: [ubuntu-20.04]
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          path: udm-iptv
      - name: Setup Dependencies
        run: sudo apt-get install devscripts debhelper
      - name: Build Package
        run: |
          cd udm-iptv
          debuild -uc -us --lintian-opts --profile debian
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          if-no-files-found: error
          path: |
            *.deb
            *.build*
            *.changes
            *.dsc